#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

OUTPUT=pdf
MAIN=main

mkdir -p $OUTPUT
rm -rf $OUTPUT/*

(pdflatex --file-line-error --synctex=1 --output-directory=$OUTPUT $MAIN.tex) || exit
(biber $OUTPUT/$MAIN) || exit
(pdflatex --file-line-error --synctex=1 --output-directory=$OUTPUT $MAIN.tex) || exit
(pdflatex --file-line-error --synctex=1 --output-directory=$OUTPUT $MAIN.tex) || exit
(makeindex $OUTPUT/$MAIN.idx) || exit
(pdflatex --file-line-error --synctex=1 --output-directory=$OUTPUT $MAIN.tex) || exit
open pdf/main.pdf || exit